# Generated by Django 4.2.15 on 2024-10-28 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильные ответы')),
                ('incorrect_answers', models.IntegerField(default=0, verbose_name='Неправильные ответы')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Всего вопросов')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Сертификат выдан')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
            },
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user_exam_result',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.question', verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.answer', verbose_name='Выбранный ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.duration', verbose_name='Продолжительность курса'),
        ),
        migrations.DeleteModel(
            name='UserExamResult',
        ),
        migrations.AddField(
            model_name='testresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.exam', verbose_name='Экзамен'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.exam', verbose_name='Экзамен'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
