# Generated by Django 4.2.15 on 2024-10-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_useranswer_userexamresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='kaspi',
            field=models.CharField(default=1, max_length=14, verbose_name='Номер каспи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('kaspi', 'Kaspi'), ('freedom_pay', 'Freedom Pay')], default=1, max_length=15, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачено'), ('failed', 'Не удалось'), ('refunded', 'Возвращено')], default='pending', max_length=10, verbose_name='Статус оплаты'),
        ),
    ]
