# Generated by Django 4.2.15 on 2024-10-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_purchase_kaspi_purchase_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_hours', models.IntegerField(default=0, verbose_name='Количество часов')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Продолжительности',
                'verbose_name_plural': 'Продолжительности',
            },
        ),
    ]
