# Generated by Django 4.2.15 on 2024-10-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='progress_percentage',
        ),
    ]
