# Generated by Django 4.2.15 on 2024-10-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kz', 'Казахский')], default=1, max_length=2, verbose_name='Язык курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='duration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='course.duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='has_promotion',
            field=models.BooleanField(default=False, verbose_name='Акция применима'),
        ),
    ]
