# Generated by Django 4.2.15 on 2024-10-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_language_purchase_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='has_promotion',
        ),
        migrations.AddField(
            model_name='course',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_promotion',
            field=models.BooleanField(default=False, verbose_name='Акция применима'),
        ),
    ]
