# Generated by Django 4.2.15 on 2024-11-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат'),
        ),
    ]
