# Generated by Django 4.2.15 on 2024-10-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_category_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.duration', verbose_name='Продолжительности курса'),
            preserve_default=False,
        ),
    ]
