# Generated by Django 4.2.15 on 2024-10-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='correct_answers_required',
            field=models.IntegerField(default=1, verbose_name='Количество правильных ответов для получения сертификата'),
            preserve_default=False,
        ),
    ]
