# Generated by Django 4.2.15 on 2024-10-31 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_verificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12, verbose_name='ИИН')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('workplace', models.CharField(max_length=100, verbose_name='Место работы')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('education_diploma', models.FileField(blank=True, null=True, upload_to='diplomas', verbose_name='Диплом об образовании')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дополнительная информация',
                'verbose_name_plural': 'Дополнительные информации',
            },
        ),
    ]
